export const AUDIT_EVENT_TYPES = {
  authLoginSucceeded: 'auth.login.succeeded',
  authSessionRefreshed: 'auth.session.refreshed',
  authSessionLoggedOut: 'auth.session.logged_out',
  companyCreated: 'admin.company.created',
  companyUpdated: 'admin.company.updated',
  companyActivated: 'admin.company.activated',
  companyDeactivated: 'admin.company.deactivated',
  locationCreated: 'admin.location.created',
  locationUpdated: 'admin.location.updated',
  locationActivated: 'admin.location.activated',
  locationDeactivated: 'admin.location.deactivated',
  departmentCreated: 'admin.department.created',
  departmentUpdated: 'admin.department.updated',
  departmentActivated: 'admin.department.activated',
  departmentDeactivated: 'admin.department.deactivated',
  userCreated: 'admin.user.created',
  userUpdated: 'admin.user.updated',
  userAccessActivated: 'admin.user.access_activated',
  userAccessDeactivated: 'admin.user.access_deactivated',
  userRoleAssigned: 'admin.user_role.assigned',
  userRoleRemoved: 'admin.user_role.removed',
  voucherPosted: 'accounting.voucher.posted',
  bookingCreated: 'crm.booking.created',
  saleContractCreated: 'crm.sale_contract.created',
  payrollRunPosted: 'payroll.run.posted',
  attachmentUploadInitiated: 'attachment.upload.initiated',
  attachmentUploadFinalized: 'attachment.upload.finalized',
  attachmentLinked: 'attachment.link.created',
  attachmentLinkRemoved: 'attachment.link.removed',
  attachmentArchived: 'attachment.archived',
} as const;

export const AUDIT_DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;
