'use client';

import type { ReactNode } from 'react';
import { Printer } from 'lucide-react';

import { Button, cn } from '@real-capita/ui';

import { printCurrentPage } from '../../lib/output';

export interface PrintableReportMetaItem {
  label: string;
  value: ReactNode;
  wide?: boolean;
}

export interface PrintableReportSummaryRow {
  label: ReactNode;
  value: ReactNode;
  note?: ReactNode;
}

export interface PrintableReportDataColumn<TRecord> {
  key: string;
  header: ReactNode;
  render: (record: TRecord, index: number) => ReactNode;
  align?: 'left' | 'center' | 'right';
  className?: string;
}

const alignClassName = {
  left: 'text-left',
  center: 'text-center',
  right: 'text-right',
} as const;

export const PrintableReportLayout = ({
  children,
  className,
  orientation = 'portrait',
  testId = 'printable-report',
}: {
  children: ReactNode;
  className?: string;
  orientation?: 'portrait' | 'landscape';
  testId?: string;
}) => (
  <article
    className={cn(
      'printable-report-layout',
      orientation === 'landscape'
        ? 'printable-report-landscape'
        : 'printable-report-portrait',
      className,
    )}
    data-print-orientation={orientation}
    data-testid={testId}
  >
    {children}
  </article>
);

export const PrintableReportHeader = ({
  activeCompany,
  additionalMetaItems = [],
  brandName = 'Real Capita ERP',
  classificationLabel = 'Confidential - internal use only',
  companyName,
  dataSourceNote,
  generatedAt,
  generatedBy,
  outputLabel,
  periodLabel,
  subtitle,
  title,
}: {
  activeCompany: string;
  additionalMetaItems?: PrintableReportMetaItem[];
  brandName?: string;
  classificationLabel?: ReactNode;
  companyName?: string;
  dataSourceNote?: ReactNode;
  generatedAt: ReactNode;
  generatedBy?: ReactNode;
  outputLabel?: ReactNode;
  periodLabel: ReactNode;
  subtitle?: ReactNode;
  title: string;
}) => {
  const metadata: PrintableReportMetaItem[] = [
    { label: 'Active company', value: activeCompany },
    { label: 'Report period', value: periodLabel },
    { label: 'Generated at', value: generatedAt },
    { label: 'Generated by', value: generatedBy ?? 'Current session' },
  ];

  metadata.push(...additionalMetaItems);

  if (dataSourceNote) {
    metadata.push({ label: 'Data source', value: dataSourceNote, wide: true });
  }

  if (outputLabel) {
    metadata.push({ label: 'Output', value: outputLabel });
  }

  return (
    <header className="printable-report-header">
      <div className="printable-report-brand-row">
        <div>
          <p className="printable-report-brand">{brandName}</p>
          {companyName ? (
            <p className="printable-report-company">{companyName}</p>
          ) : null}
        </div>
        <p className="printable-report-classification">{classificationLabel}</p>
      </div>
      <div className="printable-report-title-block">
        <h1>{title}</h1>
        {subtitle ? <p>{subtitle}</p> : null}
      </div>
      <PrintableReportMetaGrid items={metadata} />
    </header>
  );
};

export const PrintableReportFooter = ({
  generatedAt,
  note = 'Confidential - internal use only.',
  pageNumberLabel = 'Page',
  showPageCounter = false,
  systemName = 'Real Capita ERP',
}: {
  generatedAt: ReactNode;
  note?: ReactNode;
  pageNumberLabel?: string;
  showPageCounter?: boolean;
  systemName?: ReactNode;
}) => (
  <footer className="printable-report-footer">
    <div>
      <p>{systemName}</p>
      <p>Generated at {generatedAt}</p>
    </div>
    <div className="printable-report-footer-note">
      <p>{note}</p>
      {showPageCounter ? (
        <p>
          {pageNumberLabel}{' '}
          <span
            aria-label="Browser print page number"
            className="printable-report-page-counter"
          />
        </p>
      ) : null}
    </div>
  </footer>
);

export const PrintableReportMetaGrid = ({
  items,
}: {
  items: PrintableReportMetaItem[];
}) => (
  <dl className="printable-report-meta-grid">
    {items.map((item) => (
      <div
        className={cn(
          'printable-report-meta-item',
          item.wide && 'printable-report-meta-item-wide',
        )}
        key={item.label}
      >
        <dt>{item.label}</dt>
        <dd>{item.value}</dd>
      </div>
    ))}
  </dl>
);

export const PrintableReportSection = ({
  children,
  className,
  subtitle,
  title,
}: {
  children: ReactNode;
  className?: string;
  subtitle?: ReactNode;
  title: string;
}) => (
  <section className={cn('printable-report-section', className)}>
    <div className="printable-report-section-header">
      <h2>{title}</h2>
      {subtitle ? <p>{subtitle}</p> : null}
    </div>
    {children}
  </section>
);

export const PrintableReportSummaryTable = ({
  rows,
}: {
  rows: PrintableReportSummaryRow[];
}) => (
  <table className="printable-report-summary-table">
    <tbody>
      {rows.map((row, index) => (
        <tr key={`${String(row.label)}-${index}`}>
          <th scope="row">{row.label}</th>
          <td>{row.value}</td>
          {row.note ? <td>{row.note}</td> : null}
        </tr>
      ))}
    </tbody>
  </table>
);

export const PrintableReportDataTable = <TRecord,>({
  caption,
  columns,
  emptyLabel = 'No rows returned for the selected report filters.',
  getRowKey,
  rows,
}: {
  caption?: ReactNode;
  columns: Array<PrintableReportDataColumn<TRecord>>;
  emptyLabel?: ReactNode;
  getRowKey?: (record: TRecord, index: number) => string;
  rows: TRecord[];
}) => (
  <table className="printable-report-data-table">
    {caption ? <caption>{caption}</caption> : null}
    <thead>
      <tr>
        {columns.map((column) => (
          <th
            className={cn(
              alignClassName[column.align ?? 'left'],
              column.className,
            )}
            key={column.key}
            scope="col"
          >
            {column.header}
          </th>
        ))}
      </tr>
    </thead>
    <tbody>
      {rows.length > 0 ? (
        rows.map((row, rowIndex) => (
          <tr key={getRowKey ? getRowKey(row, rowIndex) : rowIndex}>
            {columns.map((column) => (
              <td
                className={cn(
                  alignClassName[column.align ?? 'left'],
                  column.className,
                )}
                key={column.key}
              >
                {column.render(row, rowIndex)}
              </td>
            ))}
          </tr>
        ))
      ) : (
        <tr>
          <td colSpan={columns.length}>{emptyLabel}</td>
        </tr>
      )}
    </tbody>
  </table>
);

export const PrintableReportNote = ({ children }: { children: ReactNode }) => (
  <aside className="printable-report-note">{children}</aside>
);

export const PrintActionButton = ({
  disabled = false,
  label = 'Print',
  onPrint = printCurrentPage,
}: {
  disabled?: boolean;
  label?: string;
  onPrint?: () => void;
}) => (
  <Button
    className="screen-only min-w-0"
    disabled={disabled}
    onClick={onPrint}
    size="sm"
    type="button"
    variant="outline"
  >
    <Printer className="h-4 w-4 shrink-0" />
    <span className="truncate">{label}</span>
  </Button>
);
